// <auto-generated />
using System;
using Lekkerbek.Web.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lekkerbek.Web.Migrations
{
    [DbContext(typeof(LekkerbekDbContext))]
    [Migration("20210306113611_BestellingEnBesteldGerecht")]
    partial class BestellingEnBesteldGerecht
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.BesteldGerecht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BestellingId")
                        .HasColumnType("int");

                    b.Property<int>("GerechtId")
                        .HasColumnType("int");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("GerechtId");

                    b.ToTable("BesteldeGerechten");
                });

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Betaald")
                        .HasColumnType("bit");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tijdslot")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.Gerecht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prijs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Gerechten");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Categorie = "Sandwiches",
                            Naam = "Ruebens Style Pastrami (Homemade)",
                            Omschrijving = "Mierikswortel, zuurkool, augurk 1, parmezaan",
                            Prijs = 9.5m
                        },
                        new
                        {
                            Id = -2,
                            Categorie = "Sandwiches",
                            Naam = "Green tea smoked salmon",
                            Omschrijving = "Crostini's , vinaigrette,  frisse sla, pickle",
                            Prijs = 9.5m
                        },
                        new
                        {
                            Id = -3,
                            Categorie = "Sandwiches",
                            Naam = "Mozzarella di bufala",
                            Omschrijving = "Parmezaan, pesto, rucola, zontomaat, walnoot",
                            Prijs = 9m
                        },
                        new
                        {
                            Id = -4,
                            Categorie = "Sandwiches",
                            Naam = "Steambun crispy chicken",
                            Omschrijving = "Bosui, rode peper, sesam, homemade stickysaus",
                            Prijs = 8.5m
                        },
                        new
                        {
                            Id = -5,
                            Categorie = "Sandwiches",
                            Naam = "Torta pizza",
                            Omschrijving = "Frisse sla, hummus, geroosterde veggies, avocado",
                            Prijs = 8m
                        },
                        new
                        {
                            Id = -6,
                            Categorie = "Salades",
                            Naam = "Salade geitenkaas",
                            Omschrijving = "Bessenhoning, mosterddressing, noten",
                            Prijs = 11m
                        },
                        new
                        {
                            Id = -7,
                            Categorie = "Salades",
                            Naam = "Green Tea Smoked salmon",
                            Omschrijving = "Pickle, groene kruiden, frisse salade",
                            Prijs = 10.5m
                        },
                        new
                        {
                            Id = -8,
                            Categorie = "Salades",
                            Naam = "Mozzarella di Bufala",
                            Omschrijving = "Parmezan, zongedroogde tomaat, pesto",
                            Prijs = 15m
                        },
                        new
                        {
                            Id = -9,
                            Categorie = "Salades",
                            Naam = "Asian salad met veggies",
                            Omschrijving = "Sesamdressing, avocado, frisse salade",
                            Prijs = 16m
                        },
                        new
                        {
                            Id = -10,
                            Categorie = "Vleesgerechten",
                            Naam = "Petto di pollo ripieno",
                            Omschrijving = "Kip gevuld met mozzarella, champignons en spinazie",
                            Prijs = 17.25m
                        },
                        new
                        {
                            Id = -11,
                            Categorie = "Vleesgerechten",
                            Naam = "Scaloppina alla casalinga",
                            Omschrijving = "Varkensfilets met ham en champignon-roomsaus",
                            Prijs = 18m
                        },
                        new
                        {
                            Id = -12,
                            Categorie = "Vleesgerechten",
                            Naam = "Filetto del maestro",
                            Omschrijving = "Varkenshaas met ham en kaas in knoflookroomsaus",
                            Prijs = 20.75m
                        },
                        new
                        {
                            Id = -13,
                            Categorie = "Vleesgerechten",
                            Naam = "Bocconcini della mamma",
                            Omschrijving = "Kalsflapjes in salie-witte wijnsaus",
                            Prijs = 21.5m
                        },
                        new
                        {
                            Id = -14,
                            Categorie = "Visgerechten",
                            Naam = "Trota salmonata",
                            Omschrijving = "Zalmforel in totmaten-knoflooksaus",
                            Prijs = 18m
                        },
                        new
                        {
                            Id = -15,
                            Categorie = "Visgerechten",
                            Naam = "Salmona in griglia",
                            Omschrijving = "Gegrilde zalm, geserveerd met 2 sauzen",
                            Prijs = 22.5m
                        },
                        new
                        {
                            Id = -16,
                            Categorie = "Visgerechten",
                            Naam = "Pesce spada in griglia",
                            Omschrijving = "Zwaardvisfilet van de gril, geserveerd met 2 sauzen",
                            Prijs = 18.5m
                        },
                        new
                        {
                            Id = -17,
                            Categorie = "Visgerechten",
                            Naam = "Salmona alla Siciliana",
                            Omschrijving = "Zalm met klappertjes en parika in kruidige tomatensaus",
                            Prijs = 21.5m
                        });
                });

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Postcode")
                        .HasColumnType("int");

                    b.Property<string>("StraatEnNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "guy.marckelbach@ucll.be",
                            Naam = "Guy Marckelbach",
                            Postcode = 3272,
                            StraatEnNummer = "Teststraat 120",
                            Telefoonnummer = "012345670",
                            Woonplaats = "Testelt"
                        },
                        new
                        {
                            Id = -2,
                            Email = "elise.coenen@ucll.be",
                            Naam = "Elise Coenen",
                            Postcode = 3272,
                            StraatEnNummer = "Teststraat 121",
                            Telefoonnummer = "012345671",
                            Woonplaats = "Testelt"
                        },
                        new
                        {
                            Id = -3,
                            Email = "henk.verelst@ucll.be",
                            Naam = "Henk Verelst",
                            Postcode = 3272,
                            StraatEnNummer = "Teststraat 122",
                            Telefoonnummer = "012345672",
                            Woonplaats = "Testelt"
                        },
                        new
                        {
                            Id = -4,
                            Email = "david.urting@ucll.be",
                            Naam = "David Urting",
                            Postcode = 3272,
                            StraatEnNummer = "Teststraat 123",
                            Telefoonnummer = "012345673",
                            Woonplaats = "Testelt"
                        });
                });

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.BesteldGerecht", b =>
                {
                    b.HasOne("Lekkerbek.Web.Models.Entities.Bestelling", "Bestelling")
                        .WithMany()
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lekkerbek.Web.Models.Entities.Gerecht", "Gerecht")
                        .WithMany()
                        .HasForeignKey("GerechtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Gerecht");
                });

            modelBuilder.Entity("Lekkerbek.Web.Models.Entities.Bestelling", b =>
                {
                    b.HasOne("Lekkerbek.Web.Models.Entities.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });
#pragma warning restore 612, 618
        }
    }
}
